import {test,expect} from "@playwright/test";
test("all pages load without script errors or horizontal overflow",async({page})=>{
 const errors=[];page.on("pageerror",e=>errors.push(e.message));
 for(const path of ["index.html","buyer.html","seller.html","properties.html","turkey-property.html","portfolios.html","portfolio.html","auction.html","payment.html","property.html","coordination.html","coordination-service.html?service=title"]){
  await page.goto("/"+path);
  await expect(page.locator("[data-mode-label]")).toContainText("Test mode");
  await expect.poll(()=>page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth+1)).toBe(true);
 }
 await page.goto("/properties.html");
 const turkey=page.locator(".property-marketplace > .property-row").nth(2);
 await expect(turkey.locator(".property-location")).toHaveText("Turkey");
 await expect(turkey.locator("h2")).toHaveText("Address awaiting confirmation");
 await expect(turkey.locator(".property-facts strong")).toHaveText(["$7,500,000","NA","NA / NA","NA"]);
 await turkey.getByRole("link",{name:"View / Prepare Interest",exact:true}).click();
 await expect(page).toHaveURL(/\/turkey-property\.html$/);
 await expect(page.getByRole("heading",{name:"Address awaiting confirmation",exact:true})).toBeVisible();
 await expect(page.getByRole("link",{name:"Watch the YouTube video"})).toHaveAttribute("href","https://www.youtube.com/watch?v=MUdBlpLWFEY");
 await page.getByRole("link",{name:"Prepare Interest",exact:true}).click();
 await expect(page).toHaveURL(/buyer\.html\?address=/);
 await expect(page.locator("#buyer-offer-address")).toHaveValue("Address awaiting confirmation, Turkey");
 await expect(page.locator("#buyer-offer-amount")).toHaveValue("7500000");
 expect(new URL(page.url()).searchParams.has("auction")).toBe(false);
 expect(errors).toEqual([]);
});
test("150-property portfolio shows a $150,000 success fee",async({page})=>{
 await page.goto("/portfolio.html");
 await expect(page.locator("#portfolio-fee")).toHaveText("$150,000");
 await expect(page.locator("#portfolio-fee-note")).toHaveText("$1,000 × 150 properties");
});
test("buyer interest without an auction requires choosing a listing",async({page})=>{
 await page.goto("/buyer.html?address=Address%20awaiting%20confirmation%2C%20Turkey&price=7500000");
 await page.locator("#buyer-name").fill("Unlinked Buyer");
 await page.locator("#buyer-email").fill("unlinked-buyer@example.com");
 await page.locator("#buyer-confirmation").check();
 await page.getByRole("button",{name:"Submit Buyer Interest",exact:true}).click();
 await expect(page).toHaveURL(/payment\.html\?role=buyer$/);
 await page.locator("#payment-consent").check();
 await page.locator("#payment-submit").click();
 await expect(page).toHaveURL(/auction\.html\?view=buyer&select=1&address=/);
 await expect(page.locator("#auction-select")).toHaveValue("");
 await expect(page.locator("#auction-select option:checked")).toHaveText("Address awaiting confirmation, Turkey · No active auction");
 await expect(page.locator("#auction-content")).toBeHidden();
 await expect(page.locator("#auction-select option[value='video-property']")).toHaveCount(0);
 await page.locator("#auction-select").selectOption("demo-grapevine");
 await expect(page.locator("#auction-title")).toHaveText("805 Vineyard Crossing, Grapevine, TX 76051");
 await expect(page.locator("#bid-form")).toBeVisible();
 await page.goto("/payment.html?role=buyer");
 await expect(page.locator("#payment-credit")).toHaveText("$1.00 test");
 await expect(page.locator("#payment-submit")).toHaveText("Auction →");
 await page.locator("#payment-submit").click();
 await expect(page).toHaveURL(/auction\.html\?view=buyer&select=1&address=/);
 await expect(page.locator("#auction-select")).toHaveValue("");
 await expect(page.locator("#auction-select option:checked")).toHaveText("Address awaiting confirmation, Turkey · No active auction");
 await expect(page.locator("#auction-content")).toBeHidden();
});
test("every sample property opens its own auction through buyer participation",async({page})=>{
 test.setTimeout(120000);
 await page.goto("/properties.html");
 const listings=await page.locator('.property-marketplace a[href^="property.html?"]').evaluateAll(links=>links.map(link=>{
  const params=new URL(link.href).searchParams;
  return {id:params.get("auction"),address:params.get("address")};
 }));
 expect(listings).toHaveLength(20);
 expect(listings.every(listing=>listing.id&&listing.address)).toBe(true);
 expect(new Set(listings.map(listing=>listing.id)).size).toBe(20);
 listings.sort((a,b)=>Number(b.id==="demo-grapevine")-Number(a.id==="demo-grapevine"));
 for(const [index,{address,id}] of listings.entries()){
  await test.step(address,async()=>{
   await page.goto("/properties.html");
   await page.locator('.property-marketplace a[href^="property.html?auction='+id+'&"]').click();
   expect(new URL(page.url()).searchParams.get("auction")).toBe(id);
   await expect(page).toHaveURL(/property\.html\?/);
   await expect(page.locator("#property-detail-address")).toHaveText(address);
   await expect(page.getByRole("link",{name:"Coordinate This Property"})).toHaveCount(0);
   await expect(page.getByRole("heading",{name:"Prepare buyer interest",exact:true})).toBeVisible();
   await page.getByRole("link",{name:"Prepare Interest",exact:true}).click();
   await expect(page.locator("#buyer-offer-address")).toHaveValue(address);
   await page.locator("#buyer-name").fill("Property Buyer");
   await page.locator("#buyer-email").fill("property-buyer@example.com");
   await page.locator("#buyer-confirmation").check();
   await page.getByRole("button",{name:"Submit Buyer Interest",exact:true}).click();
   await expect(page).toHaveURL(/payment\.html\?role=buyer$/);
   if(index===0)await page.locator("#payment-consent").check();
   else await expect(page.locator("#payment-submit")).toHaveText("Auction →");
   await page.locator("#payment-submit").click();
   await expect(page).toHaveURL(new RegExp("auction\\.html\\?id="+id+"&view=buyer$"));
   await expect(page.locator("#auction-select")).toHaveValue(id);
   await expect(page.locator("#auction-select option:checked")).toHaveText(address);
   await expect(page.locator("#auction-title")).toHaveText(address);
   await expect(page.locator("#bid-form")).toBeVisible();
  });
 }
});
test("older address-only Plano interest opens the matching auction with existing credit",async({page})=>{
 const address="2605 Preston Meadow Court, Plano, TX 75093";
 await page.goto("/buyer.html?address="+encodeURIComponent(address)+"&price=548000");
 await page.locator("#buyer-name").fill("Existing Plano Buyer");
 await page.locator("#buyer-email").fill("existing-plano@example.com");
 await page.locator("#buyer-confirmation").check();
 await page.getByRole("button",{name:"Submit Buyer Interest",exact:true}).click();
 await expect(page).toHaveURL(/payment\.html\?role=buyer$/);
 await page.locator("#payment-consent").check();
 await page.locator("#payment-submit").click();
 await expect(page).toHaveURL(/auction\.html\?id=demo-plano&view=buyer$/);
 await expect(page.locator("#auction-title")).toHaveText(address);
 await page.goto("/payment.html?role=buyer");
 await expect(page.locator("#payment-credit")).toHaveText("$1.00 test");
 await expect(page.locator("#payment-submit")).toHaveText("Auction →");
 await page.locator("#payment-submit").click();
 await expect(page).toHaveURL(/auction\.html\?id=demo-plano&view=buyer$/);
 await expect(page.locator("#auction-select")).toHaveValue("demo-plano");
 await expect(page.locator("#auction-title")).toHaveText(address);
});
test("buyer payment gate, bidding, persistent outcome and both perspectives",async({page})=>{
 await page.goto("/buyer.html?auction=demo-property&address=4218%20Maple%20Ridge%20Drive");
 await page.locator("#buyer-name").fill("Test Participant");
 await page.locator("#buyer-email").fill("buyer@example.com");
 await page.locator("#buyer-confirmation").check();
 await page.getByRole("button",{name:"Submit Buyer Interest",exact:true}).click();
 await expect(page).toHaveURL(/payment.html/);
 await page.locator("#payment-submit").click();
 await expect(page.locator("#payment-message")).toContainText("confirm");
 await page.locator("#payment-consent").check();
 await page.locator("#payment-submit").click();
 await expect(page).toHaveURL(/auction\.html\?id=demo-property&view=buyer$/);
 await expect(page.locator("#bid-form")).toBeVisible();
 await page.locator("#bid-amount").fill("500000");
 await page.locator("#bid-consent").check();
 await page.getByRole("button",{name:"Place bid",exact:true}).click();
 await expect(page.locator("#bid-history")).toContainText("$500,000");
 await expect(page.locator("#auction-highest")).toHaveCount(0);
 await expect(page.locator("#buyer-status")).toContainText("Your bid has been received");
 await page.reload();
 await expect(page.locator("#bid-history")).toContainText("$500,000");
 await page.locator("#test-controls summary").click();
 await page.locator("#finish-auction").click();
 await expect(page.locator("#auction-result")).toContainText("Your bid won");
 await expect(page.locator(".signal-green")).toBeVisible();
 await expect(page.locator("#bid-form")).toBeHidden();
 await page.reload();
 await expect(page.locator("#auction-result")).toContainText("Your bid won");
 await page.locator("#test-controls summary").click();
 await page.locator("#test-actor").selectOption("test-buyer-a");
 await expect(page.locator("#auction-result")).toContainText("did not win");
 await expect(page.locator(".signal-red")).toBeVisible();
 await expect(page.locator("#auction-result")).not.toContainText("$500,000");
 await page.locator("#test-actor").selectOption("test-seller");
 await expect(page.locator(".seller-winning-price")).toHaveText("$500,000");
 await expect(page.locator("#seller-fee-due")).toHaveText("$0");
 await expect(page.locator("#bid-history tr")).toHaveCount(4);
 await page.locator("#complete-sale").click();
 await expect(page.locator("#seller-fee-due")).toHaveText("$1,000");
});
test("blind auction accepts lower and equal bids without exposing competing offers",async({page})=>{
 await page.clock.install();
 await page.goto("/auction.html?id=demo-property&view=buyer");
 await expect(page.locator("#auction-count")).toHaveText("3");
 await expect(page.locator("#auction-highest, #bid-minimum, #reserve-status")).toHaveCount(0);
 await expect(page.locator(".auction-stats > div")).toHaveCount(2);
 await expect(page.locator("#bid-register")).not.toHaveAttribute("href",/price=/);
 await page.locator("#test-controls summary").click();
 await page.locator("#test-actor").selectOption("test-buyer-b");
 await expect(page.locator("#bid-amount")).toHaveValue("");
 await expect(page.locator("#bid-amount")).toHaveAttribute("min","1");
 await expect(page.locator("#bid-history tr")).toHaveCount(1);
 await expect(page.locator("#auction-content")).not.toContainText("$365,100");
 const responses=await page.evaluate(async()=>({listing:await window.MreoService.list(),buyer:await window.MreoService.auction("demo-property","buyer","test-buyer-b"),anonymous:await window.MreoService.auction("demo-property","buyer")}));
 expect(responses.listing.every(a=>!("bids" in a)&&!("highest" in a))).toBe(true);
 expect(responses.buyer.auction.bids.map(b=>b.amount)).toEqual([344000]);
 expect(responses.buyer.auction.bidCount).toBe(3);
 expect(responses.buyer.auction.viewerOutcome).toBe("submitted");
 expect(responses.anonymous.auction.bids).toEqual([]);
 await page.locator("#bid-amount").fill("300000");
 await page.clock.fastForward(6000);
 await expect(page.locator("#bid-amount")).toHaveValue("300000");
 for(const [index,amount] of ["300000","365100","365101"].entries()){
  await page.locator("#bid-amount").fill(amount);
  await page.locator("#bid-consent").check();
  await page.getByRole("button",{name:"Place bid",exact:true}).click();
  await expect(page.locator("#auction-count")).toHaveText(String(index+4));
  await expect(page.locator("#auction-message")).toHaveText("Bid placed successfully.");
  await expect(page.locator("#buyer-status")).toHaveText("Your bid has been received. Your result will be shown when the auction ends.");
 }
 await page.locator("#finish-auction").click();
 await expect(page.locator(".signal-green")).toBeVisible();
 await expect(page.locator("#auction-result")).toContainText("Your winning bid: $365,101");
 await page.locator("#test-actor").selectOption("test-buyer-a");
 await expect(page.locator(".signal-red")).toBeVisible();
 await expect(page.locator("#auction-content")).not.toContainText("$365,101");
 await page.locator("#test-actor").selectOption("test-seller");
 await expect(page.locator("#bid-history tr")).toHaveCount(6);
 await expect(page.locator(".seller-winning-price")).toHaveText("$365,101");
 await page.locator("#test-actor").selectOption("test-buyer-a");
 await expect(page.locator("#seller-private")).toBeHidden();
 await expect(page.locator("#seller-proceeds")).toHaveText("");
 await expect(page.locator("#auction-result")).toContainText("Your bid did not win");
});
test("Test Seller previews the same bids and proceeds as the owner of a submitted house",async({page})=>{
 await page.clock.install();
 await page.goto("/seller.html");
 await page.locator("#property-address").fill("123 Preview Lane");
 await page.locator("#property-city").fill("Dallas");
 await page.locator("#property-state").selectOption("TX");
 await page.locator("#property-zip").fill("75229");
 await page.locator("#property-type").selectOption("Single-family home");
 await page.locator("#property-condition").selectOption("Move-in ready");
 await page.locator("#seller-minimum").fill("400000");
 await page.locator("#seller-name").fill("House Seller");
 await page.locator("#seller-email").fill("house-seller@example.com");
 await page.locator("#seller-fee-consent").check();
 await page.locator("#seller-confirmation").check();
 await page.getByRole("button",{name:"Submit Property Information",exact:true}).click();
 await expect(page).toHaveURL(/payment\.html\?role=seller$/);
 await page.locator("#payment-consent").check();
 await page.locator("#payment-submit").click();
 await expect(page).toHaveURL(/auction\.html\?id=auction-[^&]+&view=seller$/);
 await expect(page.locator("#auction-title")).toHaveText("123 Preview Lane, Dallas, TX 75229");
 await page.clock.fastForward(31000);
 await expect(page.locator("#auction-count")).toHaveText("3");
 await expect(page.locator("#seller-private")).toBeVisible();
 await expect(page.locator("#bid-history-title")).toHaveText("All associated bids");
 await expect(page.locator("#bid-history tr")).toHaveCount(3);
 const ownerBids=await page.locator("#bid-history tr").allTextContents();
 const ownerProceeds=await page.locator("#seller-proceeds").textContent();
 const highestBid=await page.locator("#bid-history tr").first().locator("td").nth(1).textContent();
 const sellerId=await page.evaluate(()=>window.MreoService.session("seller").id);
 await page.locator("#test-controls summary").click();
 await page.locator("#test-actor").selectOption("test-seller");
 await expect(page.locator("#view-seller")).toHaveAttribute("aria-pressed","true");
 await expect(page.locator("#seller-private")).toBeVisible();
 await expect(page.locator("#bid-history tr")).toHaveText(ownerBids);
 await expect(page.locator("#seller-proceeds")).toHaveText(ownerProceeds);
 await page.locator("#test-actor").selectOption("test-buyer-a");
 await expect(page.locator("#bid-history tr")).toHaveCount(1);
 await page.locator("#view-seller").click();
 await expect(page.locator("#seller-private")).toBeHidden();
 await expect(page.locator("#seller-access-message")).toContainText("Only the listing seller");
 await expect(page.locator("#bid-history-title")).toHaveText("Your bid history");
 await expect(page.locator("#bid-history tr")).toHaveCount(1);
 await expect(page.locator("#bid-history")).toContainText("Test Buyer A");
 await page.locator("#test-actor").selectOption("test-seller");
 await expect(page.locator("#bid-history tr")).toHaveText(ownerBids);
 await page.locator("#test-actor").selectOption("");
 await expect(page.locator("#bid-history tr")).toHaveText(ownerBids);
 await expect(page.locator("#seller-proceeds")).toHaveText(ownerProceeds);
 expect(await page.evaluate(()=>window.MreoService.session("seller").id)).toBe(sellerId);
 await page.locator("#test-actor").selectOption("test-seller");
 await page.locator("#finish-auction").click();
 await expect(page.locator(".seller-winning-price")).toHaveText(highestBid);
 await expect(page.locator("#bid-history tr")).toHaveText(ownerBids);
 await page.locator("#test-actor").selectOption("");
 await expect(page.locator(".seller-winning-price")).toHaveText(highestBid);
 await expect(page.locator("#bid-history tr")).toHaveText(ownerBids);
 await expect(page.locator("#seller-proceeds")).toHaveText(ownerProceeds);
});
test("portfolio spreadsheet filters and actual Excel upload create a complete listing",async({page})=>{
 await page.goto("/buyer.html");
 await expect(page.locator(".portfolio-entry")).toHaveCount(0);
 await page.getByRole("link",{name:"Search Available Portfolios",exact:true}).click();
 await expect(page.getByRole("heading",{name:"Available Portfolios",exact:true})).toBeVisible();
 await expect(page.locator(".portfolio-entry")).toHaveCount(1);
 await page.locator(".portfolio-entry").click();
 await expect(page).toHaveURL(/\/portfolio\.html$/);
 await expect(page.locator("#portfolio-count")).toHaveText("150");
 await expect(page.locator("#portfolio-price")).toHaveText("$4,804,450");
 await expect(page.locator("#portfolio-table-body tr")).toHaveCount(150);
 await page.locator("#portfolio-condition").selectOption("Good");
 await expect(page.locator("#portfolio-table-body tr")).toHaveCount(60);
 const xlsx=await page.request.get("/data/REO-150-properties.xlsx");
 expect(xlsx.ok()).toBeTruthy();
 expect((await xlsx.body()).subarray(0,2).toString()).toBe("PK");
 await page.goto("/seller.html?kind=portfolio");
 await expect(page.locator("#single-fields")).toBeHidden();
 await page.locator("#portfolio-title").fill("Uploaded REO Portfolio");
 await page.locator("#portfolio-file").setInputFiles("data/REO-150-properties.xlsx");
 await expect(page.locator("#portfolio-upload-message")).toContainText("150 properties imported",{timeout:20000});
 await page.locator("#seller-minimum").fill("4803450");
 await page.locator("#seller-name").fill("Portfolio Seller");
 await page.locator("#seller-email").fill("seller@example.com");
 await page.locator("#seller-fee-consent").check();
 await page.locator("#seller-confirmation").check();
 await page.getByRole("button",{name:"Submit Property Information",exact:true}).click();
 await expect(page).toHaveURL(/payment.html/);
 await page.locator("#payment-consent").check();
 await page.locator("#payment-submit").click();
 await expect(page).toHaveURL(/auction.html/);
 await expect(page.locator("#auction-title")).toHaveText("Uploaded REO Portfolio");
 await expect(page.locator("#seller-reserve")).toHaveText("$4,953,450");
 await page.locator("#test-controls summary").click();
 await page.locator("#test-actor").selectOption("test-seller");
 await expect(page.locator("#seller-private")).toBeVisible();
 await expect(page.locator("#seller-reserve")).toHaveText("$4,953,450");
 await expect(page.locator("#bid-history-title")).toHaveText("All associated bids");
 await page.goto("/properties.html");
 await expect(page.locator(".portfolio-entry")).toHaveCount(0);
 await expect(page.locator("#new-listings")).not.toContainText("Uploaded REO Portfolio");
 await page.goto("/portfolios.html");
 await expect(page.locator("#new-listings")).toContainText("Uploaded REO Portfolio");
 await page.locator("#new-listings .portfolio-entry").click();
 await expect(page.locator("#portfolio-count")).toHaveText("150");
 await expect(page.locator("#portfolio-data-label")).toHaveText("Seller-provided portfolio data");
});
test("malformed portfolio input is rejected with a clear message",async({page})=>{
 await page.goto("/seller.html?kind=portfolio");
 await page.locator("#portfolio-file").setInputFiles({name:"bad.csv",mimeType:"text/csv",buffer:Buffer.from("Asset ID,Address,City,State,Condition,Reference Value\nA,1 Test St,Dallas,TX,Good,-100")});
 await expect(page.locator("#portfolio-upload-message")).toContainText("Reference Value must be a positive");
 expect(await page.locator("#portfolio-file").evaluate(el=>el.validity.valid)).toBe(false);
});

test("all sample auctions migrate without losing saved Grapevine interest, credit, or bids",async({page})=>{
 await page.goto("/auction.html");
 await expect(page.locator("#auction-select option")).toHaveCount(21);
 const before=await page.evaluate(()=>{
  const S=window.MreoService,C=window.MreoCore,state=JSON.parse(localStorage.getItem(S.key));
  state.exampleCatalogVersion=2;
  const existingIds=["demo-property","demo-portfolio","demo-fort-worth","demo-plano"];
  for(const id of Object.keys(state.auctions))if(!existingIds.includes(id))delete state.auctions[id];
  const legacy=C.createAuction({id:"video-property",title:"Featured video property",sellerId:"test-seller",minimum:7499000,now:Date.now()-31000,demo:true});
  legacy.example=true;C.seedDemo(legacy);state.auctions[legacy.id]=legacy;
  C.placeBid(state.auctions["demo-property"],{buyerId:"test-buyer-a",label:"Test Buyer A",amount:490000,paid:true});
  state.accounts["test-buyer-a"].creditCents=200;
  state.accounts["saved-buyer"]={id:"saved-buyer",name:"Saved Grapevine buyer",role:"buyer",creditCents:100,submission:{auctionId:"",title:"805 Vineyard Crossing, Grapevine, TX 76051"}};
  state.accounts["retired-buyer"]={id:"retired-buyer",name:"Retired listing buyer",role:"buyer",creditCents:100,submission:{auctionId:"video-property"}};
  const custom=C.createAuction({id:"saved-property",title:"Seller's saved property",sellerId:"test-seller",minimum:100000,demo:true});
  custom.example=false;state.auctions[custom.id]=custom;
  localStorage.setItem(S.key,JSON.stringify(state));
  return {existing:Object.fromEntries(existingIds.map(id=>[id,state.auctions[id]])),legacy,accounts:state.accounts,custom};
 });
 await page.reload();
 await expect(page.locator("#auction-select option")).toHaveCount(22);
 await expect(page.locator('#auction-select option[value="video-property"]')).toHaveCount(0);
 await expect(page.locator('#auction-select option[value="saved-property"]')).toHaveText("Seller's saved property");
 const after=await page.evaluate(()=>JSON.parse(localStorage.getItem(window.MreoService.key)));
 expect(after.exampleCatalogVersion).toBe(4);
 for(const [id,auction] of Object.entries(before.existing)){
  expect(after.auctions[id].bids).toEqual(auction.bids);
  expect(after.auctions[id].endsAt).toEqual(auction.endsAt);
 }
 expect(after.auctions["video-property"].bids).toEqual(before.legacy.bids);
 expect(after.auctions["video-property"].hidden).toBe(true);
 expect(after.accounts).toEqual(before.accounts);
 expect(after.auctions["saved-property"].endsAt).toEqual(before.custom.endsAt);
 for(const [id,title] of [["demo-fort-worth","7812 Oak Hollow Lane, Fort Worth, TX 76137"],["demo-plano","2605 Preston Meadow Court, Plano, TX 75093"],["demo-grapevine","805 Vineyard Crossing, Grapevine, TX 76051"]]){
  await page.locator("#auction-select").selectOption(id);
  await expect(page.locator("#auction-title")).toHaveText(title);
  await expect(page.locator("#auction-count")).toHaveText("3");
 }
 const retiredDraft=await page.evaluate(async()=>{
  const S=window.MreoService;
  sessionStorage.setItem(S.key+":demo:buyer",JSON.stringify({id:"retired-buyer",role:"buyer"}));
  return S.activate("buyer");
 });
 expect(retiredDraft.auctionId).toBeNull();
 await page.evaluate(()=>{
  const S=window.MreoService;
  sessionStorage.setItem(S.key+":demo:buyer",JSON.stringify({id:"saved-buyer",role:"buyer"}));
 });
 await page.goto("/auction.html?view=buyer");
 await expect(page.locator("#auction-select option:checked")).toHaveText("805 Vineyard Crossing, Grapevine, TX 76051");
 await expect(page.locator("#auction-title")).toHaveText("805 Vineyard Crossing, Grapevine, TX 76051");
 await page.goto("/payment.html?role=buyer");
 await expect(page.locator("#payment-credit")).toHaveText("$1.00 test");
 await expect(page.locator("#payment-submit")).toHaveText("Auction →");
 await page.locator("#payment-submit").click();
 await expect(page).toHaveURL(/auction\.html\?id=demo-grapevine&view=buyer$/);
 await expect(page.locator("#auction-title")).toHaveText("805 Vineyard Crossing, Grapevine, TX 76051");
 await expect(page.locator("#bid-form")).toBeVisible();
 await page.reload();
 await expect(page.locator("#auction-select option")).toHaveCount(22);
 const again=await page.evaluate(()=>JSON.parse(localStorage.getItem(window.MreoService.key)));
 for(const id of ["demo-fort-worth","demo-plano","demo-grapevine"])expect(again.auctions[id].endsAt).toBe(after.auctions[id].endsAt);
});

test("an unavailable auction never substitutes a different property",async({page})=>{
 await page.goto("/auction.html?id=missing-property&view=buyer");
 await expect(page.locator("#auction-select")).toHaveValue("");
 await expect(page.locator("#auction-content")).toBeHidden();
 await expect(page.locator("#auction-message")).toContainText("That auction is unavailable");
 await page.locator("#auction-select").selectOption("demo-grapevine");
 await expect(page).toHaveURL(/auction\.html\?id=demo-grapevine&view=buyer$/);
 await expect(page.locator("#auction-title")).toHaveText("805 Vineyard Crossing, Grapevine, TX 76051");
 await expect(page.locator("#auction-message")).toBeHidden();
});

test("changing selection during a slow auction load keeps the dropdown and heading together",async({page})=>{
 await page.goto("/auction.html");
 await expect(page.locator("#auction-title")).toHaveText("4218 Maple Ridge Drive, Dallas, TX 75229");
 await page.evaluate(()=>{
  const service=window.MreoService,original=service.auction;
  const pause=new Promise(resolve=>window.releaseAuctionRequest=resolve);
  let delayed=false;
  service.auction=async(...args)=>{
   if(args[0]==="demo-plano"&&!delayed){delayed=true;window.auctionRequestPaused=true;await pause;}
   return original(...args);
  };
 });
 await page.locator("#auction-select").selectOption("demo-plano");
 await expect.poll(()=>page.evaluate(()=>window.auctionRequestPaused)).toBe(true);
 await expect(page.locator("#auction-content")).toBeHidden();
 await page.locator("#auction-select").selectOption("demo-grapevine");
 await page.evaluate(()=>window.releaseAuctionRequest());
 await expect(page.locator("#auction-select")).toHaveValue("demo-grapevine");
 await expect(page.locator("#auction-select option:checked")).toHaveText("805 Vineyard Crossing, Grapevine, TX 76051");
 await expect(page.locator("#auction-title")).toHaveText("805 Vineyard Crossing, Grapevine, TX 76051");
});
