(()=>{"use strict";const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
 class DocumentVault{
  constructor(root,transaction){this.root=root;this.transaction=transaction;this.base=`/api/v1/transactions/${encodeURIComponent(transaction.id)}`;this.root.innerHTML=`<div class="document-list"></div><form class="upload-form"><label>Upload a transaction document<input type="file" name="file" required accept=".pdf,.doc,.docx,.jpg,.jpeg,.png,.webp,.xls,.xlsx,.csv,.txt"></label><label>Who may see it<select name="visibility"><option value="participants">All transaction participants</option><option value="buyer_agent">Buyer and MREO Agent</option><option value="seller_agent">Seller and MREO Agent</option><option value="agent_provider">Provider and MREO Agent</option><option value="agent_only">MREO Agent only</option></select></label><button class="small-button primary" type="submit">Upload securely</button></form>`;this.list=root.querySelector(".document-list");this.form=root.querySelector("form");this.form.onsubmit=event=>this.upload(event);this.root.onclick=event=>this.click(event);}
  async refresh(){try{const {documents}=await MreoIdentity.request(this.base+"/documents");this.documents=documents;this.list.innerHTML=documents.length?documents.map(document=>`<article class="document-item"><strong>${esc(document.filename)}</strong><small>${esc(document.kind)} · ${esc(document.status)} · ${Math.max(1,Math.round(document.size_bytes/1024))} KB</small><div class="document-actions"><button class="small-button" data-download="${document.id}" data-version="${document.status==="complete"?"completed":"original"}">${document.status==="complete"?"View executed PDF":"Download"}</button>${document.status==="signature_pending"?`<button class="small-button primary" data-sign="${document.id}">Review &amp; Sign</button>`:""}${this.transaction.viewerRole==="agent"&&document.status==="available"?`<button class="small-button primary" data-send-signature="${document.id}">Send for signatures</button>`:""}</div></article>`).join(""):`<div class="empty-card"><p>No documents have been added yet.</p></div>`;}catch(e){this.list.innerHTML=`<div class="empty-card"><p>${esc(e.message)}</p></div>`;}}
  async upload(event){event.preventDefault();const button=this.form.querySelector("button"),data=new FormData(this.form);button.disabled=true;try{await MreoIdentity.request(this.base+"/documents",{method:"POST",body:data});this.form.reset();await this.refresh();dispatchEvent(new CustomEvent("mreo:workspace-changed"));}catch(e){alert(e.message);}finally{button.disabled=false;}}
  async click(event){const download=event.target.closest("[data-download]"),sign=event.target.closest("[data-sign]"),send=event.target.closest("[data-send-signature]");try{if(download){download.disabled=true;const response=await MreoIdentity.request(`${this.base}/documents/${encodeURIComponent(download.dataset.download)}/download?version=${download.dataset.version}`);const blob=await response.blob(),url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download="";a.click();setTimeout(()=>URL.revokeObjectURL(url),30000);download.disabled=false;}if(sign){sign.disabled=true;const {url}=await MreoIdentity.request(`${this.base}/documents/${encodeURIComponent(sign.dataset.sign)}/signing-session`,{method:"POST",body:"{}"});open(url,"_blank","noopener");sign.disabled=false;}if(send){send.disabled=true;const recipients=this.transaction.participants.filter(person=>["buyer","seller"].includes(person.role)&&person.email).map(person=>({role:person.role,name:person.display_name||person.email,email:person.email}));if(!recipients.length)throw Error("Add the buyer or seller account to this transaction before sending a signature request.");await MreoIdentity.request(`${this.base}/documents/${encodeURIComponent(send.dataset.sendSignature)}/signatures`,{method:"POST",body:JSON.stringify({recipients,applySigningOrder:true})});await this.refresh();dispatchEvent(new CustomEvent("mreo:workspace-changed"));}}catch(e){if(download)download.disabled=false;if(sign)sign.disabled=false;if(send)send.disabled=false;alert(e.message);}}
 }
 globalThis.DocumentVault=DocumentVault;
})();
