(()=>{"use strict";const params=new URLSearchParams(location.search),perspective=params.get("perspective");if(!params.has("demo")||!["buyer","seller","agent","provider"].includes(perspective))return;
 const roleButton=document.querySelector(`[data-role="${perspective==="agent"?"buyer":perspective}"]`);roleButton?.click();const viewbar=document.querySelector(".workspace-viewbar"),controls=document.querySelector(".demo-control-strip");const hidePublicControls=()=>{if(viewbar&&!viewbar.hidden)viewbar.hidden=true;if(controls&&!controls.hidden)controls.hidden=true;};hidePublicControls();if(viewbar)new MutationObserver(hidePublicControls).observe(viewbar,{attributes:true,attributeFilter:["hidden"]});setTimeout(hidePublicControls,0);
 const labels={buyer:"Buyer",seller:"Seller",agent:"MREO Agent",provider:"Service Partner"},flows={
 buyer:[{s:"action",t:"Review the winning transaction",c:"Confirm that the property and winning bid information are correct.",a:"Confirm and continue"},{s:"waiting",t:"MREO Agent is reviewing the transaction",c:"The fictional agent is opening the buyer and seller workspaces."},{s:"action",t:"Upload proof of funds",c:"Demonstrate supplying the first requested buyer document.",a:"Simulate upload"},{s:"waiting",t:"Seller is reviewing the purchase agreement",c:"Your buyer workspace remains private while the fictional seller acts."},{s:"action",t:"Review and sign the purchase agreement",c:"Open a simulated signing step without contacting the seller directly.",a:"Review & sign"},{s:"waiting",t:"Title company is preparing closing",c:"The executed agreement and property record have moved to title."},{s:"complete",t:"Buyer demonstration complete",c:"The permanent record now carries into post-closing coordination."}],
 seller:[{s:"action",t:"Review the winning buyer result",c:"Confirm that MREO should proceed to transaction coordination.",a:"Continue through MREO"},{s:"waiting",t:"Buyer is supplying proof of funds",c:"The fictional buyer acts without receiving your contact information."},{s:"action",t:"Review the purchase agreement",c:"Demonstrate the seller-side document review.",a:"Approve for signature"},{s:"waiting",t:"Buyer is signing",c:"MREO records the fictional signature event automatically."},{s:"action",t:"Supply title and payoff information",c:"Complete the seller action requested by the title provider.",a:"Simulate submission"},{s:"complete",t:"Seller demonstration complete",c:"The transaction history preserves the auction, documents, signatures, and transfer."}],
 agent:[{s:"action",t:"Open separate buyer and seller threads",c:"The agent sees both conversations, but the participants never see each other’s thread.",a:"Open workspaces"},{s:"action",t:"Request buyer proof of funds",c:"Assign a buyer-only action through the shared task engine.",a:"Send request"},{s:"waiting",t:"Buyer is uploading proof of funds",c:"The fictional buyer completes the action automatically."},{s:"action",t:"Send purchase agreement for signature",c:"Create buyer and seller signature tasks from the same document.",a:"Send agreement"},{s:"waiting",t:"Buyer and seller are signing",c:"Fictional e-signature events update the transaction automatically."},{s:"action",t:"Release the executed agreement to title",c:"Move the permanent transaction record to the selected provider.",a:"Send to title"},{s:"complete",t:"Agent demonstration complete",c:"One chronological record now contains messages, documents, tasks, and provider events."}],
 provider:[{s:"waiting",t:"MREO Agent is preparing a title request",c:"The fictional agent shares only the records needed for this assignment."},{s:"action",t:"Accept the title assignment",c:"Open the connected property packet and confirm capacity.",a:"Accept assignment"},{s:"action",t:"Request seller payoff information",c:"The request is routed through MREO rather than direct seller contact.",a:"Send request"},{s:"waiting",t:"Seller is supplying the requested information",c:"The fictional seller’s action is recorded in the shared history."},{s:"action",t:"Upload the title commitment",c:"Add a provider-originated document to the permanent vault.",a:"Simulate upload"},{s:"complete",t:"Service-partner demonstration complete",c:"The agent, buyer, and seller receive the appropriate next actions."}]};
 const key=`mreo:experience:${perspective}`,flow=flows[perspective];let index=Math.min(Number(sessionStorage.getItem(key)||0),flow.length-1),timer=null;
 const hero=document.querySelector(".coordination-hero>div");if(hero){hero.querySelector(".section-label").textContent="MREO · Single-perspective demonstration";hero.querySelector("h1").innerHTML=`Experience as<br>${labels[perspective]}.`;hero.querySelector("p:not(.section-label)").textContent="You remain in this perspective. Fictional participants act automatically on the other side.";}
 const panel=document.createElement("section");panel.className="workspace-panel demo-story";panel.innerHTML=`<p class="section-label">Current transaction action</p><div class="demo-story-status"><span class="demo-story-light"></span><strong id="demo-story-state"></strong></div><h2 id="demo-story-title"></h2><p id="demo-story-copy"></p><div class="form-actions"><button id="demo-story-action" class="primary-button button-blue"></button><button id="demo-story-reset" class="contract-button">Start over</button></div>`;document.querySelector(".role-intro")?.before(panel);
 function advance(){index=Math.min(index+1,flow.length-1);sessionStorage.setItem(key,index);render();}
 function render(){clearTimeout(timer);const step=flow[index];panel.dataset.state=step.s;panel.querySelector("#demo-story-state").textContent=step.s==="action"?"Action needed":step.s==="waiting"?"Waiting":"Complete";panel.querySelector("#demo-story-title").textContent=step.t;panel.querySelector("#demo-story-copy").textContent=step.c;const action=panel.querySelector("#demo-story-action");action.hidden=!step.a;action.textContent=step.a||"";if(step.s==="waiting")timer=setTimeout(advance,1800);}
 panel.querySelector("#demo-story-action").onclick=advance;panel.querySelector("#demo-story-reset").onclick=()=>{index=0;sessionStorage.removeItem(key);render();};render();
})();
