(() => {"use strict";
 const $=id=>document.getElementById(id),status=$("profile-status"),app=$("profile-app"),list=$("transaction-list");let transactions=[],me=null,section="active";
 const esc=value=>String(value??"").replace(/[&<>"']/g,ch=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[ch]));
 const participantRole=value=>["buyer","seller","provider"].includes(value)?value:"";
 const roleLabel=value=>({buyer:"Buyer",seller:"Seller",provider:"Service Partner",agent:"MREO Agent"}[value]||"Participant");
 const showStatus=html=>{status.innerHTML=html;status.hidden=false;app.hidden=true;};
 function visible(){if(section==="past")return transactions.filter(t=>["complete","cancelled"].includes(t.status));if(section==="active")return transactions.filter(t=>!["complete","cancelled"].includes(t.status));if(section==="actions")return transactions.filter(t=>Number(t.action_count)>0);return transactions;}
 function render(){const rows=visible(),workspaceSection=section==="documents"?"files":"messages",labels={messages:"Open private conversation →",documents:"Open document vault →",actions:"Review required actions →"},empty={actions:"You have no outstanding action items.",messages:"Your private conversations will appear here after you submit buyer interest or a seller listing.",documents:"Document vaults will appear here with your MREO workspaces."};$("profile-section-title").textContent=document.querySelector(`[data-section="${section}"]`)?.textContent||"Workspaces";list.innerHTML=rows.length?rows.map(t=>{const query=new URLSearchParams({transaction:t.id,section:workspaceSection}),role=participantRole(t.viewer_role);if(role)query.set("role",role);return `<a class="transaction-row" href="coordination.html?${query.toString()}"><div><h3>${esc(t.title)}</h3><p>${esc(roleLabel(t.viewer_role))} · ${esc(t.kind)} · Updated ${new Date(t.updated_at).toLocaleDateString()}</p></div><div class="transaction-meta"><span class="status-chip">${esc(t.status)}</span><small>${esc(labels[section]||"Open workspace →")}</small></div></a>`}).join(""):`<div class="empty-card"><h3>Nothing here yet</h3><p>${esc(empty[section]||"Your MREO records will appear here as you participate in transactions.")}</p></div>`;}
 async function resetAll(){const button=$("profile-reset-all"),note=$("profile-reset-status"),confirmation=prompt("This permanently removes all connected test auctions, bids, workspaces, messages, files, and service activity for every account. Sign-in identities remain. Type RESET ALL to continue.");if(confirmation===null)return;if(confirmation!=="RESET ALL"){note.textContent="Reset cancelled. The confirmation must exactly match RESET ALL.";return;}button.disabled=true;note.textContent="Resetting the connected test environment…";try{await MreoIdentity.request("/api/v1/admin/reset",{method:"POST",body:JSON.stringify({confirmation})});if(globalThis.MreoService?.clear)await MreoService.clear();location.reload();}catch(error){note.textContent=error.message;button.disabled=false;}}
 async function start(){
  if(!MreoIdentity.connected()){showStatus(`<h3>Connected accounts are ready for deployment</h3><p>The public demonstration remains available without an account. Once the Cloudflare Worker is deployed, this page becomes your persistent MREO account.</p><a class="primary-button button-blue" href="experience.html">Explore MREO</a>`);return;}
  try{await MreoIdentity.init();const signed=await MreoIdentity.mountUserButton($("account-user"));if(!signed){showStatus(`<h3>Sign in to My MREO</h3><p>Create one account for every transaction in which you buy, sell, or provide services.</p><button class="primary-button button-blue" id="profile-sign-in">Sign in or create account</button>`);$("profile-sign-in").onclick=()=>MreoIdentity.openSignIn();return;}
   [me,{transactions}]=await Promise.all([MreoIdentity.request("/api/v1/me"),MreoIdentity.request("/api/v1/transactions")]);
   const roles=new Set(transactions.map(t=>participantRole(t.viewer_role)).filter(Boolean));$("profile-greeting").textContent=`Welcome${me.displayName?`, ${me.displayName}`:""}. Your access is determined separately for each transaction.`;$("summary-active").textContent=transactions.filter(t=>!["complete","cancelled"].includes(t.status)).length;$("summary-complete").textContent=transactions.filter(t=>t.status==="complete").length;$("summary-roles").textContent=roles.size;status.hidden=true;app.hidden=false;if((me.roles||[]).some(role=>["agent","admin"].includes(role))){$("profile-admin").hidden=false;$("profile-reset-all").onclick=resetAll;}render();
  }catch(e){showStatus(`<h3>My MREO could not load</h3><p>${esc(e.message)}</p>`);}
 }
 document.querySelectorAll("[data-section]").forEach(button=>button.addEventListener("click",()=>{document.querySelectorAll("[data-section]").forEach(item=>item.setAttribute("aria-selected","false"));button.setAttribute("aria-selected","true");section=button.dataset.section;render();}));start();
})();
