(()=>{"use strict";const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
 class TransactionThread{
  constructor(root,transactionId,viewerRole){this.root=root;this.transactionId=transactionId;this.viewerRole=viewerRole;this.thread=viewerRole==="agent"?"buyer_agent":null;this.root.innerHTML=`<div class="thread-tabs" hidden></div><div class="message-list" aria-live="polite"></div><form class="message-form"><textarea aria-label="Message" maxlength="8000" required placeholder="Write a message to the MREO Agent"></textarea><button class="small-button primary" type="submit">Send</button></form>`;this.tabs=root.querySelector(".thread-tabs");this.list=root.querySelector(".message-list");this.form=root.querySelector("form");if(viewerRole==="agent")this.addTabs();this.form.addEventListener("submit",event=>this.send(event));}
  addTabs(){this.tabs.hidden=false;for(const [kind,label] of [["buyer_agent","Buyer ↔ MREO"],["seller_agent","Seller ↔ MREO"],["provider_agent","Provider ↔ MREO"]]){const button=document.createElement("button");button.type="button";button.textContent=label;button.setAttribute("aria-pressed",String(kind===this.thread));button.onclick=()=>{this.thread=kind;this.tabs.querySelectorAll("button").forEach(item=>item.setAttribute("aria-pressed",String(item===button)));this.refresh();};this.tabs.append(button);}}
  endpoint(){return `/api/v1/transactions/${encodeURIComponent(this.transactionId)}/messages${this.thread?`?thread=${encodeURIComponent(this.thread)}`:""}`;}
  async refresh(){try{const data=await MreoIdentity.request(this.endpoint());this.list.innerHTML=data.messages.length?data.messages.map(message=>`<article class="message ${message.author_role===this.viewerRole?"mine":""}"><small>${esc(message.author_name||message.author_role)} · ${new Date(message.created_at).toLocaleString()}</small><div>${esc(message.body).replace(/\n/g,"<br>")}</div>${message.correction_of?'<small>Correction to an earlier message</small>':''}</article>`).join(""):`<div class="empty-card"><h3>Your private MREO thread is ready</h3><p>Write your first message below. Only you and authorized MREO personnel can read this conversation.</p></div>`;this.list.scrollTop=this.list.scrollHeight;}catch(e){this.list.innerHTML=`<div class="empty-card"><p>${esc(e.message)}</p></div>`;}}
  async send(event){event.preventDefault();const input=this.form.querySelector("textarea"),body=input.value.trim();if(!body)return;const button=this.form.querySelector("button");button.disabled=true;try{await MreoIdentity.request(`/api/v1/transactions/${encodeURIComponent(this.transactionId)}/messages`,{method:"POST",body:JSON.stringify({body,thread:this.thread})});input.value="";await this.refresh();}catch(e){alert(e.message);}finally{button.disabled=false;}}
 }
 globalThis.TransactionThread=TransactionThread;
})();
